# spring
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:jwtdb
    url: jdbc:h2:./etc/db/jwtdb;auto_server=true
    username: jwt
    password: jwt
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
#    spring boot 2.x 에서는 버그인지 잘 작동하지 않는다.
#    임시로 hibernate 로 generate 하자
#    initialization-mode: always # always 로 변경 후 initializer 한번 실행.
#    schema: classpath:data/schema-h2.sql
#    data: classpath:data/data-h2.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  pid:
    file: etc/pid/jwt.pid

# server
server:
  servlet:
    context-path: '/jwt'
    session:
      cookie:
        name: 'AUTH_GATEWAY_JWT_LOCAL_COOKIE'

  port: 8100

  tomcat:
    uri-encoding: UTF-8

# logging
logging:
  file: etc/log/jwt.log
  path: etc/log
  level:
    root: info
    org:
      springframework: info
      hibernate: info

# kong
kong:
  baseUrl: 'http://172.16.5.154/admin-api/consumers/'
  credential:
    createUri: '{consumer}/jwt'
    deleteUri: '{consumer}/jwt/{id}'
